### ISSUE TITLE
Mango to Hardklor input handover leads to an error with mzml

### ISSUE THREAD

**Issue by IwanParf** [jpm369/mango#2]
Dear Mango developers,
According to documentation, both Mango and Hardklor support mzml format as an input. However, if I provide mzml files, Mango reads them in, starts Hardklor and somehow tells it that the input files are mzxml, which then obviously leads to an error.
The following is a copy from my shell with the input files abbreviated:
.\mango.exe .\I_Parfentev_061120_201120_Synapt_XXX_F18to21.mzML 

 Mango version "2017.01 rev. 0 beta 3"

 reading .\I_Parfentev_061120_201120_Synapt_XXX_F18to21.mzML ... 100%
 reading .\I_Parfentev_061120_201120_Synapt_XXX_F18to21hk1 ...
Hardklor v2.3.0, August 14 2015
Mike Hoopmann, Mike MacCoss
Copyright 2007-2015
University of Washington
Reading from file: .\I_Parfentev_061120_201120_Synapt_XXX_F18to2.mzXML
Writing to file: .\I_Parfentev_061120_201120_Synapt_XXX_F18to2.hk2
ERROR: Failure reading input file .\I_Parfentev_061120_201120_Synapt_XXX_F18to2.mzXML
.\I_Parfentev_061120_201120_Synapt_XXX_F18to2.mzXML is invalid, or contains no spectrum.
 Error ... cannot create/read .\I_Parfentev_061120_201120_Synapt_XXX_F18to21hk1 file.

Of note, it also crops the file title and loses the last number in line "Reading from file: .\I_Parf[...]F18to2.mzXML" and following, but not for the hk1 pendant in the last line. It does so irrespective of the last character, i.e. numbers and letters. 

I am running the programs on Win 10.

Best regards,

Iwan

**Comment by jpm369** [comment]
Hi Iwan,

I have found the cause of this, it should be a pretty straightforward fix.

Jared

**Comment by IwanParf** [comment]
Hello Jared,
Thanks a lot! It was not a pressing issue for me, but downstream of the pipeline, xinteract.exe was looking for mzml files, too, so I was wondering whether one would get somehow different results if starting with mzml files. 

Best,

Iwan

**Comment by jpm369** [comment]
Hi Iwan,

I think I have fixed the issue, at least it runs and returns output on mzML files now. Grab a new copy of the windows release folder and see if it works. You'll need to use the new hardklor.exe in there as well, I can't get the old version to build on my windows machine anymore, so I had to update to the current release. 

Internally we only ever use centroided mzXMLs from msconvert as input, but I don't think you should see a big difference in the mzXML vs mzML input unless you generate them with different programs that process the raw data differently (e.g. centroiding, noise-filtering etc.). 

Please let me know if it runs on your machine
Jared

**Comment by IwanParf** [comment]
Hello Jared,
Thank you very much for your help. I've processed my data in mzML format with the new mango and hardklor and it works. Interestingly, I get roughly  10 % more identifications. Could this possibly be an effect of the new hardklor? I'll reprocess my old mzMLs with the new softwares to double-check.

Best regards and thanks a lot!

Iwan

**Comment by jpm369** [comment]
I'm glad everything seems to work!

It is possible, it looks like Hardklor has received some performance tweaks in the past few years since the original build.

If you were so curious to find out, you could run the old version of Hardklor from the previous release to generate the .hk1 and .hk2 files (it'll look like hardklor.exe filename.conf1, hardklor.exe filename.conf2, you might have to fix the file names in the bottom of the conf files), and then put them in a directory with your mzMLs and use the fixed version of mango - it'll use the hardklor files in the directory if they exist already.
