### ISSUE TITLE
xlink positions within proteins

### ISSUE THREAD

**Issue by IwanParf** [jpm369/mango#3]
Dear Mango developers,
First of all, sorry, if this is rather a xlinkprophet issue.
I have processed my data with Mango, comet, xinteract, iprophet and xlinkprophet. Now, the final results table does not contain xlink positions within the protein. Did I miss something or is it by design? In case of the latter, can you suggest a feasible way to retrieve the xlink position? E.g. by running a uniprot-like peptide search, retrieve the start position of the peptide and calculate the xlink position within the protein?

Best regards,

Iwan

**Comment by jpm369** [comment]
Hi Iwan,

Sorry for the slow response. That functionality is included in a separate tool from xlinkprophet. Please visit http://xlinkdb.gs.washington.edu/, and there is an "upload new data" form where you should be able to upload your xlinkprophet output. Xlinkdb will handle the site assignment and mapping, and send you a table where you can browse your results. 

Let me know if that works or not. I'll leave this issue open in the mean time.

Jared

**Comment by jpm369** [comment]
Hi Iwan,

Please see https://github.com/brucelab/xlinkprophet, we have added a convertXLinkProphetXLStoUpload7col.pl to generate an xlinkdb compatible upload file.  There is an option to pass the argument FASTA=/path/to/fasta to generate the extra two columns with the cross-link protein residue positions.

Jared

**Comment by IwanParf** [comment]
Hello Jared,
thank you very much for your (not slow at all) response! I already had a paragraph of follow-up error description ready, but now after trying again it worked. Thank you very much! I exclusively worked with the XlinkProphet.pl file, which did not need a params file, so I was first confused what to provide. It would therefore be nice to specify in the Readme.md to generate it with the runXlinkProphet.pl. 

Thanks again for your help!

Best,

Iwan
